export const ACCESSORY_IMAGES: Record<string, any> = {
  hat_beanie: require("@/assets/accessories/hat_beanie.png"),
  hat_tophat: require("@/assets/accessories/hat_tophat.png"),
  hat_crown: require("@/assets/accessories/hat_crown.png"),
  hat_baseball: require("@/assets/accessories/hat_baseball.png"),
  hat_wizard: require("@/assets/accessories/hat_wizard.png"),
  hat_party: require("@/assets/accessories/hat_party.png"),
  hat_cowboy: require("@/assets/accessories/hat_cowboy.png"),
  hat_santa: require("@/assets/accessories/hat_santa.png"),
  hat_chef: require("@/assets/accessories/hat_chef.png"),
  hat_beret: require("@/assets/accessories/hat_beret.png"),

  glasses_round: require("@/assets/accessories/glasses_round.png"),
  glasses_monocle: require("@/assets/accessories/glasses_monocle.png"),
  glasses_nerd: require("@/assets/accessories/glasses_nerd.png"),
  glasses_diamond: require("@/assets/accessories/glasses_diamond.png"),
  glasses_star: require("@/assets/accessories/glasses_star.png"),
  glasses_heart: require("@/assets/accessories/glasses_heart.png"),

  sunglasses_aviator: require("@/assets/accessories/sunglasses_aviator.png"),
  sunglasses_rainbow: require("@/assets/accessories/sunglasses_rainbow.png"),
  sunglasses_pixel: require("@/assets/accessories/sunglasses_pixel.png"),
  sunglasses_galaxy: require("@/assets/accessories/sunglasses_galaxy.png"),

  clothes_hoodie: require("@/assets/accessories/clothes_hoodie.png"),
  clothes_tuxedo: require("@/assets/accessories/clothes_tuxedo.png"),
  clothes_cape: require("@/assets/accessories/clothes_cape.png"),
  clothes_labcoat: require("@/assets/accessories/clothes_labcoat.png"),
  clothes_leather: require("@/assets/accessories/clothes_leather.png"),
  clothes_spacesuit: require("@/assets/accessories/clothes_spacesuit.png"),
  clothes_robe: require("@/assets/accessories/clothes_robe.png"),
  clothes_kimono: require("@/assets/accessories/clothes_kimono.png"),

  bag_backpack: require("@/assets/accessories/bag_backpack.png"),
  bag_treasure: require("@/assets/accessories/bag_treasure.png"),
  bag_magic: require("@/assets/accessories/bag_magic.png"),

  badge_star: require("@/assets/accessories/badge_star.png"),
  badge_heart: require("@/assets/accessories/badge_heart.png"),
  badge_shield: require("@/assets/accessories/badge_shield.png"),
  badge_lightning: require("@/assets/accessories/badge_lightning.png"),

  wings_fairy: require("@/assets/accessories/wings_fairy.png"),
  wings_angel: require("@/assets/accessories/wings_angel.png"),
  wings_butterfly: require("@/assets/accessories/wings_butterfly.png"),
  wings_dragon: require("@/assets/accessories/wings_dragon.png"),
  wings_phoenix: require("@/assets/accessories/wings_phoenix.png"),
  wings_rainbow: require("@/assets/accessories/wings_rainbow.png"),

  pet_kitten: require("@/assets/accessories/pet_kitten.png"),
  pet_puppy: require("@/assets/accessories/pet_puppy.png"),
  pet_bunny: require("@/assets/accessories/pet_bunny.png"),
  pet_hamster: require("@/assets/accessories/pet_hamster.png"),
  pet_fox: require("@/assets/accessories/pet_fox.png"),
  pet_owl: require("@/assets/accessories/pet_owl.png"),
  pet_dragon: require("@/assets/accessories/pet_dragon.png"),
  pet_unicorn: require("@/assets/accessories/pet_unicorn.png"),
  pet_phoenix: require("@/assets/accessories/pet_phoenix.png"),
};

export const ACCESSORY_POSITIONS: Record<string, { top: number; left: number; size: number }> = {
  hat: { top: -20, left: 0, size: 60 },
  glasses: { top: 30, left: 0, size: 50 },
  sunglasses: { top: 30, left: 0, size: 50 },
  clothes: { top: 55, left: 0, size: 65 },
  bag: { top: 50, left: 45, size: 40 },
  badge: { top: 40, left: -40, size: 30 },
  wings: { top: 20, left: 0, size: 90 },
  pet: { top: 70, left: 50, size: 45 },
};
